import type * as Type from '$lib/schemas/components/textTypes';

export const styles: Type.TextStyleOptions = {
	h1: 'font-heading text-5xl font-normal md:text-7xl lg:text-9xl text-primary-800 dark:text-primary-300',
	h2: 'font-heading text-5xl font-normal md:text-6xl lg:text-8xl text-primary-800 dark:text-primary-300',
	h3: 'font-heading text-4xl font-normal md:text-5xl lg:text-7xl text-primary-800 dark:text-primary-300',
	h4: 'font-heading text-4xl font-normal md:text-5xl lg:text-6xl text-primary-800 dark:text-primary-300',
	h5: 'font-heading text-3xl font-normal md:text-4xl lg:text-5xl text-primary-800 dark:text-primary-300',
	h6: 'font-heading text-3xl font-normal md:text-4xl lg:text-4xl text-primary-800 dark:text-primary-300',
	h7: 'font-heading text-2xl font-normal md:text-3xl lg:text-3xl text-primary-800 dark:text-primary-300',
	h8: 'font-heading text-xl font-normal md:text-2xl lg:text-2xl text-primary-800 dark:text-primary-300',
	h9: 'font-heading text-lg font-normal md:text-xl lg:text-xl text-primary-800 dark:text-primary-300',
	h10: 'font-heading text-base font-normal md:text-lg lg:text-lg text-primary-800 dark:text-primary-300',
	h11: 'font-heading text-sm font-normal md:text-base lg:text-lg text-primary-800 dark:text-primary-300',
	h12: 'font-heading text-sm font-normal md:text-base lg:text-base text-primary-800 dark:text-primary-300',
	para1: 'font-body text-xs leading-4 font-normal tracking-normal text-neutral-700 dark:text-neutral-300',
	para2: 'font-body text-xs leading-5 font-normal tracking-normal md:text-sm md:leading-5 text-neutral-700 dark:text-neutral-300',
	para3: 'font-body text-sm leading-5 font-normal tracking-normal text-neutral-700 dark:text-neutral-300',
	para4: 'font-body text-sm leading-6 font-normal tracking-normal md:text-base md:leading-6 text-neutral-700 dark:text-neutral-300',
	para5: 'font-body text-base leading-6 font-normal tracking-normal text-neutral-700 dark:text-neutral-300',
	paraBase: 'font-body text-base leading-7 font-normal tracking-normal md:text-lg md:leading-7 text-neutral-700 dark:text-neutral-300',
	para6: 'font-body text-lg leading-7 font-normal tracking-normal md:text-xl md:leading-7 text-neutral-700 dark:text-neutral-300',
	para7: 'font-body text-xl leading-8 font-normal tracking-normal md:text-2xl md:leading-8 text-neutral-700 dark:text-neutral-300',
	para8: 'font-body text-2xl leading-8 font-normal tracking-normal md:text-3xl md:leading-9 lg:text-3xl lg:leading-10 text-neutral-700 dark:text-neutral-300',
	para9: 'font-body text-3xl leading-9 font-normal tracking-normal md:text-4xl md:leading-9 lg:text-4xl lg:leading-9 text-neutral-700 dark:text-neutral-300',
	para10: 'font-body text-4xl leading-10 font-normal tracking-normal md:text-5xl md:leading-10 text-neutral-700 dark:text-neutral-300',
	eyebrow: 'font-mono text-xs leading-3 font-normal tracking-tight md:text-sm md:leading-4',
	// eyebrow: 'font-special text-sm text-neutral-300 dark:text-neutral-500 tracking-tighter',
	sr: 'sr-only'
};
